<?php

class Whatsapp extends Skype
{
    public $chatting;
    public $voiceMessages;

    public function __construct($screenSharing, $audioCalling, $chatting, $voiceMessages)
    {
        parent::__construct($screenSharing, $audioCalling);
        $this->chatting = $chatting;
        $this->voiceMessages = $voiceMessages;
    }

    public function xInfo()
    {
        parent::xInfo(); // TODO: Change the autogenerated stub
        echo "Can we do chatting ? '$this->chatting'.<br>";
        echo "Voices messages? '$this->voiceMessages'.<br>";
    }
}